# Generated by Django 3.0.8 on 2020-11-06 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poemgen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_word', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='poem',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='poem',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
