# Generated by Django 3.0.8 on 2020-11-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poemgen', '0002_auto_20201106_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoemDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=450)),
            ],
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
